name: Deploy Google Apps Script

on:
#  push:
#    branches: [ main ]
#    paths:
#      - 'gas/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Create CLASP_AUTH file
        run: |
          echo '${{ secrets.CLASP_AUTH }}' > ~/.clasprc.json

      - name: Push to GAS
        run: |
          cd gas
          clasp push -f
