name: Deploy Google Apps Script

on:
#  push:
#    branches: [ main ]
#    paths:
#      - 'gas/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7
        with:
          node-version: '20'

      - name: Install clasp
        run: npm install -g @google/clasp

      - name: Create CLASP_AUTH file
        run: |
          echo '${{ secrets.CLASP_AUTH }}' > ~/.clasprc.json

      - name: Push to GAS
        run: |
          cd gas
          clasp push -f
